import 'package:dio/dio.dart';

import '../../core/error/failures.dart';

/// Calls the neural ChipComposer server (your GPU box) which returns a Song
/// JSON (instruments/patterns/arrangement) generated by the model trained on
/// NES-MDB. The 8-bit sound is still rendered on-device by the Rust engine.
class RemoteComposerDataSource {
  final Dio _dio;
  final String Function() _baseUrl;

  RemoteComposerDataSource(this._dio, this._baseUrl);

  Future<Map<String, dynamic>> composeSong(double targetSeconds) async {
    final url = _baseUrl().trim();
    try {
      final res = await _dio.post<Map<String, dynamic>>(
        '$url/compose',
        data: {'seconds': targetSeconds, 'temperature': 0.7, 'max_new': 2600},
        options: Options(
          sendTimeout: const Duration(seconds: 20),
          receiveTimeout: const Duration(seconds: 120),
        ),
      );
      final data = res.data;
      if (data == null) {
        throw const ComposerFailure('Neural server returned empty response.');
      }
      return data;
    } on DioException catch (e) {
      throw ComposerFailure('Neural server error: ${e.message}');
    }
  }
}
