// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse`

/// Synthesize a song (JSON) into raw 16-bit PCM, expanded to `target_seconds`.
Future<PcmAudio> synthesizePcm({
  required String songJson,
  required double targetSeconds,
}) => RustLib.instance.api.crateApiSynthSynthesizePcm(
  songJson: songJson,
  targetSeconds: targetSeconds,
);

/// Synthesize a song into a complete WAV file.
Future<Uint8List> synthesizeWav({
  required String songJson,
  required double targetSeconds,
}) => RustLib.instance.api.crateApiSynthSynthesizeWav(
  songJson: songJson,
  targetSeconds: targetSeconds,
);

/// Synthesize a song into an MP3 file at the given CBR bitrate (kbps).
Future<Uint8List> synthesizeMp3({
  required String songJson,
  required double targetSeconds,
  required int bitrateKbps,
}) => RustLib.instance.api.crateApiSynthSynthesizeMp3(
  songJson: songJson,
  targetSeconds: targetSeconds,
  bitrateKbps: bitrateKbps,
);

/// Begin a streaming playback session for the song expanded to `target_seconds`.
/// Returns format info; pull audio with [`stream_next_chunk`].
Future<StreamInfo> streamStart({
  required String songJson,
  required double targetSeconds,
}) => RustLib.instance.api.crateApiSynthStreamStart(
  songJson: songJson,
  targetSeconds: targetSeconds,
);

/// Pull the next chunk (up to `max_frames` stereo frames) of 16-bit PCM.
/// Returns an empty list once playback is complete.
Future<Uint8List> streamNextChunk({required int maxFrames}) =>
    RustLib.instance.api.crateApiSynthStreamNextChunk(maxFrames: maxFrames);

/// Stop and release the current streaming session.
Future<void> streamStop() => RustLib.instance.api.crateApiSynthStreamStop();

/// 16-bit PCM audio result handed back to Dart.
class PcmAudio {
  final int sampleRate;
  final int channels;

  /// Number of mono frames (samples per channel).
  final int frameCount;

  /// Interleaved little-endian signed 16-bit PCM.
  final Uint8List bytes;

  const PcmAudio({
    required this.sampleRate,
    required this.channels,
    required this.frameCount,
    required this.bytes,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^
      channels.hashCode ^
      frameCount.hashCode ^
      bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PcmAudio &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          frameCount == other.frameCount &&
          bytes == other.bytes;
}

/// Metadata for a streaming playback session.
class StreamInfo {
  final int sampleRate;
  final int channels;
  final BigInt totalFrames;

  const StreamInfo({
    required this.sampleRate,
    required this.channels,
    required this.totalFrames,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^ channels.hashCode ^ totalFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamInfo &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          totalFrames == other.totalFrames;
}
